services:
  customer-backend:
    build:
      context: ./customer_website_be
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8002:8002"
    depends_on:
      - store-backend

  store-backend:
    build:
      context: ./store_website_be
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8000:8000"

  customer-frontend:
    build:
      context: ./customer_website_fe
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  store-frontend:
    build:
      context: ./store_website_fe
      dockerfile: Dockerfile
    ports:
      - "8081:8081"

  qcommerce-website:
    build:
      context: ./qcommerce_website
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    depends_on:
      - customer-frontend
      - store-frontend
